# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
