# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190124_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plt_icon',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
